# Generated by Django 4.1.7 on 2023-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_fun_director_fun_verdict_alter_fun_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fun',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
