# Generated by Django 4.1.7 on 2023-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_fun_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='fun',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
