# Generated by Django 4.1.7 on 2023-04-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
